### ISSUE TITLE
Unable to read grib2 data (return data from geovariable object)

### ISSUE THREAD

**Issue by jcruce17** [nctoolbox/nctoolbox#133] opened 2021-09-14 01:59 UTC
I'm attempting to read MRMS radar data from here:
https://mrms.ncep.noaa.gov/data/2D/ReflectivityAtLowestAltitude/

I grabbed a sample grib2 file. I've used nctoolbox for many years and this is the first time I've run into an issue reading data. The variable I'm having issues with is the reflectivity data (VAR209-3-57_FROM_161-0-0_altitude_above_msl).

Here is the simple read code:

`nc=ncgeodataset('MRMS_ReflectivityAtLowestAltitude_00.50_20210913-194039.grib2');
time=nc.geovariable('time');
time=time.data(:);
altitude=nc.geovariable('altitude_above_msl');
altitude=altitude.data(:);
lat=nc.geovariable('lat');
lat=lat.data(:);
lon=nc.geovariable('lon');
lon=lon.data(:);
lowestalt=nc.geovariable('VAR209-3-57_FROM_161-0-0_altitude_above_msl');
lowestalt=squeeze(lowestalt.data(:,:,:,:));`

When I run the script, I get the following error:
Error using ncdataset/readdata (line 494)
Java exception occurred:
java.lang.UnsupportedOperationException: Unsupported DRS type = 41

	at ucar.nc2.grib.grib2.Grib2Drs.factory(Grib2Drs.java:59)

	at
    ucar.nc2.grib.grib2.Grib2SectionDataRepresentation.getDrs(Grib2SectionDataRepresentation.java:73)

	at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:271)

	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:983)

	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)

	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:722)

	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1941)

	at ucar.nc2.Variable.reallyRead(Variable.java:859)

	at ucar.nc2.Variable._read(Variable.java:831)

	at ucar.nc2.Variable.read(Variable.java:709)

	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:518)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:502)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:526)

	at ucar.nc2.Variable.read(Variable.java:695)

	at ucar.nc2.Variable.read(Variable.java:669)

Error in ncdataset/data (line 171)
                    d = obj.readdata(variable, first, last, stride);

Error in ncgeodataset/subsref (line 630)
                            B = builtin('subsref',obj,g);

Error in ncvariable/somedata (line 406)
                data = obj.dataset.data(name, first, last, stride);

Error in ncvariable/data (line 189)
                d = somedata(obj, 1, first, last, stride);

Error in ncgeovariable/subsref (line 1116)
                                        sref = obj.data(first, last, stride);

Error in Radar_read_test (line 11)
lowestalt=squeeze(lowestalt.data(:,:,:,:));

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Thoughts on what's going on here??

**Comment by hohonuuli** [comment] 2021-09-14 15:22
I confirmed that I can duplicate this. Steps to reproduce:

Download data set from <https://mrms.ncep.noaa.gov/data/2D/ReflectivityAtLowestAltitude/> and extract it. Looks like those files are only kept for the last day or so.

Here's the minimal code to reproduce the error:

```matlab
% Adjust file name as needed
nc = ncgeodataset('MRMS_ReflectivityAtLowestAltitude_00.50_20210913-135923.grib2')
lowestalt=nc.geovariable('VAR209-3-57_FROM_161-0-0_altitude_above_msl');
lowestalt=squeeze(lowestalt.data(:,:,:,:));
```

Error:

```text
Error using ncdataset/readdata (line 494)
Java exception occurred:
java.lang.UnsupportedOperationException: Unsupported DRS type = 41
	at ucar.nc2.grib.grib2.Grib2Drs.factory(Grib2Drs.java:59)
	at ucar.nc2.grib.grib2.Grib2SectionDataRepresentation.getDrs(Grib2SectionDataRepresentation.java:73)
	at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:282)
	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:983)
	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)
	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:720)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1957)
	at ucar.nc2.Variable.reallyRead(Variable.java:841)
	at ucar.nc2.Variable._read(Variable.java:813)
	at ucar.nc2.Variable.read(Variable.java:691)
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:519)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:503)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:527)
	at ucar.nc2.Variable.read(Variable.java:677)
	at ucar.nc2.Variable.read(Variable.java:651)

Error in ncdataset/data (line 171)
                    d = obj.readdata(variable, first, last, stride);

Error in ncgeodataset/subsref (line 630)
                            B = builtin('subsref',obj,g);

Error in ncvariable/somedata (line 406)
                data = obj.dataset.data(name, first, last, stride);

Error in ncvariable/data (line 189)
                d = somedata(obj, 1, first, last, stride);

Error in ncgeovariable/subsref (line 1116)
                                        sref = obj.data(first, last, stride);
```

**Comment by hohonuuli** [comment] 2021-09-14 15:28
Grib errors are by far the most commonly reported problems by users of nctoolbox. It looks like [this particular one has been addressed](https://www.unidata.ucar.edu/support/help/MailArchives/idv/msg06937.html) in more recent versions of the Java Grib library. Unfortunately, the link to the issue is broken so I can't see which version addresses this. Also, due to a PITA version conflict between the Apache HTTP Client libraries built into to Matlab (which are super old)  and the ones used by the most recent versions of NetCDF-Java (less old), I can't upgrade nctoolbox to the latest and greatest NetCDF-Java (which would likely fix this error).

**Comment by hohonuuli** [comment] 2021-09-14 15:29
Sadly, I'm closing this issue as it can't be addressed until Matlab removes the ancient HTTP Client libraries.

**Closed as completed by hohonuuli** 2021-09-14 15:29 UTC

**Comment by jcruce17** [comment] 2021-09-14 15:40
Thanks for looking into this. Is there any way around the issue? Older versions of nctoolbox or conversion from grib? Anything I can try on my end?

**Comment by jcruce17** [comment] 2021-09-14 15:41
> Sadly, I'm closing this issue as it can't be addressed until Matlab removes the ancient HTTP Client libraries.

Thanks for looking into this. Is there any way around the issue? Older versions of nctoolbox or conversion from grib? Anything I can try on my end?

**Comment by hohonuuli** [comment] 2021-09-14 16:03
As a quick test for a workaround, I grabbed the latest NetCDF-Java uber jar from [GitHub](https://github.com/Unidata/thredds/releases/tag/v4.6.17), removed all the existing jars from `nctoolbox/java` and dropped the new jar in. Unfortunatly, the Java API has changed. 

```text
>> nc = ncgeodataset('/Users/brian/Downloads/MRMS_ReflectivityAtLowestAltitude_00.50_20210913-135923.grib2')

nc = 

  ncgeodataset with properties:

     location: '/Users/brian/Downloads/MRMS_ReflectivityAtLowestAltitude_00.50_20210913-135923.grib2'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {7×1 cell}

>> lowestalt=nc.geovariable('VAR209-3-57_FROM_161-0-0_altitude_above_msl');
Unrecognized function or variable 'escapeName'.

Error in ncdataset/findvariable (line 454)
                v = obj.netcdf.findVariable(ucar.nc2.NetcdfFile.escapeName(variable))

Error in ncdataset/attributes (line 262)
                v = obj.findvariable(variable);

Error in ncgeodataset/geovariable (line 391)
                att = obj.attributes(variableName);

Error in ncgeodataset/subsref (line 630)
                            B = builtin('subsref',obj,g);
```

When I get some free time, I can look into what happened to the `escapeName` method. (But I'm swamped at work at the moment)

**Comment by jcruce17** [comment] 2021-09-14 16:26
> As a quick test for a workaround, I grabbed the latest NetCDF-Java uber jar from [GitHub](https://github.com/Unidata/thredds/releases/tag/v4.6.17), removed all the existing jars from `nctoolbox/java` and dropped the new jar in. Unfortunatly, the Java API has changed.
> 
> ```
> >> nc = ncgeodataset('/Users/brian/Downloads/MRMS_ReflectivityAtLowestAltitude_00.50_20210913-135923.grib2')
> 
> nc = 
> 
>   ncgeodataset with properties:
> 
>      location: '/Users/brian/Downloads/MRMS_ReflectivityAtLowestAltitude_00.50_20210913-135923.grib2'
>        netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
>     variables: {7×1 cell}
> 
> >> lowestalt=nc.geovariable('VAR209-3-57_FROM_161-0-0_altitude_above_msl');
> Unrecognized function or variable 'escapeName'.
> 
> Error in ncdataset/findvariable (line 454)
>                 v = obj.netcdf.findVariable(ucar.nc2.NetcdfFile.escapeName(variable))
> 
> Error in ncdataset/attributes (line 262)
>                 v = obj.findvariable(variable);
> 
> Error in ncgeodataset/geovariable (line 391)
>                 att = obj.attributes(variableName);
> 
> Error in ncgeodataset/subsref (line 630)
>                             B = builtin('subsref',obj,g);
> ```
> 
> When I get some free time, I can look into what happened to the `escapeName` method. (But I'm swamped at work at the moment)

Thanks so much. I appreciate you looking into this.

**Comment by jcruce17** [comment] 2022-06-11 14:55
Has anything changed with recent versions of Matlab that would remedy this closed issue with grib2 data? Thanks.
